# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.loader.efi.efiSysMountPoint = "/efi";

  fileSystems."/" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@nixos" "compress=zstd" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/999bb59b-d212-496b-867d-b0e54d9f16a3";

  fileSystems."/home" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" ];
    };

  fileSystems."/mnt/root" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "compress=zstd" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/disk/by-uuid/5fa4fdc5-9574-4fa0-b351-50559993bb29";
      fsType = "btrfs";
      options = [ "subvol=@media" "compress=zstd" ];
    };

  fileSystems."/mnt/hdd" =
    { device = "/dev/disk/by-uuid/5fa4fdc5-9574-4fa0-b351-50559993bb29";
      fsType = "btrfs";
      options = [ "compress=zstd" ];
    };

  fileSystems."/var/lib/containers/storage" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [
      "subvol=@containers-storage"
      "compress=zstd"
    ];
  };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/7F16-80BA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
