# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &personal A57D4A240C8BC704260A0E6F800214724BE3A82F
  - &m00n age1pzfypmreq7znfawswqes7c0hcfehna6du69exhd6rq403sxtny9spje4kz
  - &m00nsrv age18847yw0y9zrvf9gmeu2m62vhukpc653nddvyjeazlc9gxz8dyecqmwsyga
  - &bastion age1st7xhv6tx87lgh4prgr382uvau4tstqxzzjj2ds7vqr5qd7hu53qw5qt3z
creation_rules:
  - path_regex: secrets/k3s.yaml
    key_groups:
    - pgp:
      - *personal
      age:
      - *m00nsrv
      - *bastion
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *m00n
  - path_regex: host/m00n/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *m00n
  - path_regex: hosts/m00nsrv/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *m00nsrv
  - path_regex: hosts/bastion/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *bastion
