# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &personal F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  # Desktops
  - &kepler age1gwv3knvgfrk26ythtrs2ed4235x8tu79lad459vx3e92krth6phq6t3ca3
  - &ember age1pzfypmreq7znfawswqes7c0hcfehna6du69exhd6rq403sxtny9spje4kz
  - &tide age1g75gk36leqv55yjdu2ulxutnkgye9f82ezhrkcllss3wejc6wewq6kyavs
  # Servers
  - &ganymede age18847yw0y9zrvf9gmeu2m62vhukpc653nddvyjeazlc9gxz8dyecqmwsyga
  - &beacon age1st7xhv6tx87lgh4prgr382uvau4tstqxzzjj2ds7vqr5qd7hu53qw5qt3z
creation_rules:
  - path_regex: secrets/k3s.yaml
    key_groups:
    - pgp:
      - *personal
      age:
      - *ganymede
      - *beacon
  - path_regex: ^secrets/[^/]+\.(yaml|json|env|ini|txt)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *kepler
      - *ember
      - *tide
  - path_regex: systems/x86_64-linux/kepler/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *kepler
  - path_regex: systems/x86_64-linux/ember/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *ember
  - path_regex: systems/x86_64-linux/ganymede/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *ganymede
  - path_regex: systems/aarch64-linux/beacon/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *beacon
  - path_regex: systems/x86_64-linux/tide/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *personal
      age:
      - *tide
