passwords:
    root: ENC[AES256_GCM,data:m3X/Rf4x3Z1Kq9U7D5jOcqjr0A8BhvVu87S4B+M4jlK7VqlVw4D4Sps/2bHbp/za9QubIjpagczM5tw7qpb5KFjLTwgJbVh+XA==,iv:1e4+I5c3EiTzMi++adSqFEJidFSjfO+f55rALfBl1YA=,tag:ZSnK/JIAF/wi9J7i4C6rCw==,type:str]
    m00n: ENC[AES256_GCM,data:tODTilUrPxbjdRJ7Lc0aPlQ8lmg2TATNRgX+t3Gdz6alPTW0DiHncpYu1SoTLk6luZQMzzRSiNp9mfmd7W/dDx/CjzASHFhqxA==,iv:5xj+h7bIUkfv+qMnXBDuVFg/Qhgq2tHUeCperxOh9zE=,tag:a9c49zQR/2nctYhWBdMccg==,type:str]
atuin:
    session: ENC[AES256_GCM,data:FAdCG1Ija26ay5uQP4slLyCZMO5udAS1d0Rxaqk6s+Y=,iv:5Ac0dvAufjJvqIWuvY8P2mIgMYfX4LWkVdmmQDCYXU0=,tag:PEcqxwsxgMLfjPtwM71G3A==,type:str]
sops:
    age:
        - recipient: age1g75gk36leqv55yjdu2ulxutnkgye9f82ezhrkcllss3wejc6wewq6kyavs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZjdhcFlscUZvTTgwSHNz
            Z3c2UG5LNlpnM0lCVzdXWnB3dmIyMU9uKzNrClVPYW5nWWJRbDFHZStsUjl1QndO
            Z0dNUGluTHMwUzdlendaU05EcGU0cVUKLS0tIGNqb0p0djlaU2NUSXRLZ3FMOElG
            QUJlbUFJTXp1VlZBTC9uRi81QitSdE0KZNLpHRx5db9QT/0HZ5mqtI7idDxHvXQR
            pIvA7vvbPI4fXM97mc2/pfpayRYYk3RASoORo8jF4/nUPzfOAyi4lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T23:57:38Z"
    mac: ENC[AES256_GCM,data:Wdo6ga5wgEwaq4aiOuFDkjS2OqHbd37Uvv+LK0Jaq5TdiA/uf85ZCiMf1rX9x+n+QTf5381dr9Gt5rzbbpGesH2FTGtqKr2d87zGPclbXbsRNsOWvCha0YmCi5H9HVzjAlqzUZY9DuUgRDbrnr/v4iekHGVFeJNvIrHVo7gLKSQ=,iv:ZC7TkLncBv65USE9ZDim8SZKpzS07l8ZrOYYhLh41tc=,tag:SCVBQh05ld3GXmyWG+4S/A==,type:str]
    pgp:
        - created_at: "2025-12-29T16:30:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC0EwVK2S0BUSAQdAX60KtNoJ9EvUaKrda7LduzPWupC5pLBcCUgmvAMcZWIw
            LFz25ev1TmEsxBTwU5LcF9DD5SqMj99HNLuPd6kkbW7p0Ggy52UiEnv6E1/jIlsS
            0l4BpeuJClI0JNyEYPaIFWtj8GHZabaP0FHjP9DFh6gqZOqlyPHlqKdlxjZrlO7p
            Uomj+/Tv7Bewyj/kqT6HmuVae+E4kg9Wl7zdf0gPLm1ISoXG0+Aw0uRdhCCDEhUy
            =QKnp
            -----END PGP MESSAGE-----
          fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
    unencrypted_suffix: _unencrypted
    version: 3.11.0
