passwords:
    root: ENC[AES256_GCM,data:0pKIPSr+bkpD6h7rREDg2jLDuxE1YMff8omyjXfrYZpsimYXqVIPzSzhTFqMcZhcrvBuLydvkpHe592tQfVV7C+W+iEdvpg4tA==,iv:Zk3KpQXpYbfXk21Kf8aQczpDGLoY37nMxP3rNGrBdkg=,tag:hv0BEGsgVF7yWihkY0bICw==,type:str]
    m00n: ENC[AES256_GCM,data:sNt3gNaFxxWwfiC+3ezuVmK3GgGbPUPACPOwPvFbyGmAA8WDDEB4Lj6s0Y+v5pJ62qCD3TnkEGlIAEiIlFAoPJR+HLPJL0jPtA==,iv:DNUPgI0nVPCI5pDzII1H/YVOOVPwG5kFrs9frXy6/WA=,tag:VtvzgPChNEZm9wzStm7tfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pzfypmreq7znfawswqes7c0hcfehna6du69exhd6rq403sxtny9spje4kz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSTJKVHl2K3NuRm1IdWhE
            eHVQNUR1ODZRaW5pZGdLNWxvWTlFTlBFSFVRCmdyNDY0NytBY1drOVhqWWdEQVh1
            ZlVCSkFnbDdnUWQwUXI4dlYyS2dLdGsKLS0tIGFEamgxLzVZVWVLaU13ZUU1Y1hk
            ME9EUWtCS0E2REh3YVRpVzBTMmx2bk0KEHpCVSeQPHMuQ+jCqIAbYOufLJNhbjb4
            2uNh1HxFvHNBnFUHYYigfTmhXr+QyQyxT902MaOuhtZO/0R7h5tAjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T01:36:22Z"
    mac: ENC[AES256_GCM,data:HmQIYJUrqEviD8FyxsAkI6Ao11dNwNzkAHwL1J9KBrYwwBu3nte3f8qJwMyxJg+cmEvnAhmCycFOo7ooz9O/ewxJQCtVSdWkeQceEQP/sGuRe0W08OVbsqJj+7YF4+cjgriTeZm2Wy4IBW9Ex/vChGAhSFHn286GSsEVMcveMUM=,iv:2F5SYiyaJyBXtRQtAVD6pnCbvuLVqNiWHfCa/Il/iCk=,tag:ZYWYnTn6HgSuIRSdBSMV1g==,type:str]
    pgp:
        - created_at: "2025-03-30T00:58:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DvGVQGhLDA1gSAQdA0aZ55U3v5aqCsFTO3cGUBhh+l94P018Iv0jORjI6fiUw
            tmuAzIMRu3GG2uX0/IEmuhYp4N+TsXi6Or1Zz453nNqEjbGQSfJXT3wlHcx7szBY
            0l4BpyDiXfEyPUzrLx6eMXWjgWxvQZn6zcgB72KaPYEnz3W2+4TBJkulIodrBVmg
            pVGEJ5/VizaYrJYSNuJ23aIv8hPVDWGTXLzAClOZbi6eD6TY4JIrVFi31bNlziEX
            =9RrS
            -----END PGP MESSAGE-----
          fp: A57D4A240C8BC704260A0E6F800214724BE3A82F
    unencrypted_suffix: _unencrypted
    version: 3.9.4
