self: super: {
	pywalfox-native =
		super.pywalfox-native.overrideAttrs (old: {
				postInstall = ''
					${old.postInstall or ""}
					mkdir -p $out/lib/mozilla/native-messaging-hosts
					cat > $out/lib/mozilla/native-messaging-hosts/pywalfox.json <<EOF
					{
					  "name": "pywalfox",
					  "description": "Automatically theme your browser using the colors generated by Pywal",
					  "path": "$out/bin/pywalfox",
					  "type": "stdio",
					  "allowed_extensions": [ "pywalfox@frewacom.org" ]
					}
					EOF
				'';
			});
}
