apiVersion: k3d.io/v1alpha5
kind: Simple
image: rancher/k3s:v1.32.4-k3s1
options:
  k3s:
    extraArgs:
      - arg: --kubelet-arg=feature-gates=KubeletInUserNamespace=true
        nodeFilters:
          - server:*
          - agent:*
