passwords:
    root: ENC[AES256_GCM,data:m3X/Rf4x3Z1Kq9U7D5jOcqjr0A8BhvVu87S4B+M4jlK7VqlVw4D4Sps/2bHbp/za9QubIjpagczM5tw7qpb5KFjLTwgJbVh+XA==,iv:1e4+I5c3EiTzMi++adSqFEJidFSjfO+f55rALfBl1YA=,tag:ZSnK/JIAF/wi9J7i4C6rCw==,type:str]
    m00n: ENC[AES256_GCM,data:tODTilUrPxbjdRJ7Lc0aPlQ8lmg2TATNRgX+t3Gdz6alPTW0DiHncpYu1SoTLk6luZQMzzRSiNp9mfmd7W/dDx/CjzASHFhqxA==,iv:5xj+h7bIUkfv+qMnXBDuVFg/Qhgq2tHUeCperxOh9zE=,tag:a9c49zQR/2nctYhWBdMccg==,type:str]
sops:
    age:
        - recipient: age1gwv3knvgfrk26ythtrs2ed4235x8tu79lad459vx3e92krth6phq6t3ca3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWW5zY1I2REFrSXROdHNX
            dmtBeHU3M1R3aENSUS9wcVBJOG1CMHV3RWpzCm1OdzV6dms4M2M0QlU2dUlPMnNM
            V0s2Rm5Wc1dtVFRqNGVUV2pCQ051Q28KLS0tIGlHdkJIR25jcVl5RXRUMkdtTlpp
            dlRuazFVNUlkMTgvRzdtcDBlVTZmM0UKsErsPzCSZvRAfElqDiHLXaNmPsGQq3P0
            uwpoU1wbLtZG4wp8AWpa1PQqz5qS92gyinMXIOQBqX/tP+UuvedXBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T19:28:14Z"
    mac: ENC[AES256_GCM,data:C2KTbocaWVnH93UDgkgNh0pMizOe53MBprrVgUc4g6oLbIsJV2qS+Ribf51lA89mw5w2gO6R5VKeJfRODUDiq305vGj8JknquINEmdikKRE0yWIcisZfvbcAm4X9/x7fL//2mnYT+qldZ1Dsd56TQtvxp0U3XhZ78akzpUCKYr4=,iv:Ckxvgn7MBZzbIE4EkMzvszpeRrTttFLcMsFogFKxqbQ=,tag:PTqvEgGecELrRGZEFfBlZA==,type:str]
    pgp:
        - created_at: "2025-05-03T18:05:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC0EwVK2S0BUSAQdAOZ/bw8DtO7lHlv2HZV4EZd+T7BtWqLr0p0WDYL9kLFMw
            6tu54173GHI4OEmHoNaxuxwTviWNKg6Vl6a2iqYTCOb7is+rrxBMqlMqIKOxRem1
            0l4BtrKZ3cjV1prJUgASfAYz23m4XVOcVrPPj++svRa4g1vhxip6TrL03latn5bv
            ct9TSTiRDXhzISiZxToPvkA6r4mbm0MD9kvkxTRR4yRIOpFBXLIZoaZr3eDWwSLU
            =USTc
            -----END PGP MESSAGE-----
          fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
    unencrypted_suffix: _unencrypted
    version: 3.10.1
