passwords:
    root: ENC[AES256_GCM,data:m3X/Rf4x3Z1Kq9U7D5jOcqjr0A8BhvVu87S4B+M4jlK7VqlVw4D4Sps/2bHbp/za9QubIjpagczM5tw7qpb5KFjLTwgJbVh+XA==,iv:1e4+I5c3EiTzMi++adSqFEJidFSjfO+f55rALfBl1YA=,tag:ZSnK/JIAF/wi9J7i4C6rCw==,type:str]
    m00n: ENC[AES256_GCM,data:tODTilUrPxbjdRJ7Lc0aPlQ8lmg2TATNRgX+t3Gdz6alPTW0DiHncpYu1SoTLk6luZQMzzRSiNp9mfmd7W/dDx/CjzASHFhqxA==,iv:5xj+h7bIUkfv+qMnXBDuVFg/Qhgq2tHUeCperxOh9zE=,tag:a9c49zQR/2nctYhWBdMccg==,type:str]
sops:
    age:
        - recipient: age1gwv3knvgfrk26ythtrs2ed4235x8tu79lad459vx3e92krth6phq6t3ca3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ0hob3BoL0JQZTB2dEhR
            eHRrcmUzeEg1SWZ5NERmSTJ3bUpNanNWaVMwCmMzTkN1QzRQWXB6S25ZUUU4Sml5
            VkVvS2laWGRBQzRSRTdoeWd6dXRZR1UKLS0tIGlaenRPUG5XTUo4V3hFT2p5U3pX
            NlZxNHpjS29iUEhvOUtHeGFBU1ZpV0kKXz03cHPHe7Wzk8maB7pI4pWbVUr9dtiv
            Kzd5+5Jjfx4uuYxfB/wi6oIiEdGD42d2siN2WPBMuUD02g+J3NXArg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T19:28:14Z"
    mac: ENC[AES256_GCM,data:C2KTbocaWVnH93UDgkgNh0pMizOe53MBprrVgUc4g6oLbIsJV2qS+Ribf51lA89mw5w2gO6R5VKeJfRODUDiq305vGj8JknquINEmdikKRE0yWIcisZfvbcAm4X9/x7fL//2mnYT+qldZ1Dsd56TQtvxp0U3XhZ78akzpUCKYr4=,iv:Ckxvgn7MBZzbIE4EkMzvszpeRrTttFLcMsFogFKxqbQ=,tag:PTqvEgGecELrRGZEFfBlZA==,type:str]
    pgp:
        - created_at: "2025-04-16T15:59:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DvGVQGhLDA1gSAQdAlQU2hxe7UWO8gW2rchOHAAAtI1NA/zkq1zEca1NVi2Ew
            Saq266pNBVGcv26L4cQ/0bXb/jeX9Zy9IsMgOUluyJpPmLyj/6H6HumdPF58JJDr
            0l4BsVebJUQBPJrh5UGODJufwd1tgpWeWQaqkY/6G+JUcsKQ+sLoPY8mN1vu0oCB
            sZtq/OnaYrNq4GxtD7B8Tk/ZbXVDWbcHOUS0C3lxXgoCIImLwnsBfjo/lgqf6t/z
            =FIe4
            -----END PGP MESSAGE-----
          fp: A57D4A240C8BC704260A0E6F800214724BE3A82F
    unencrypted_suffix: _unencrypted
    version: 3.10.1
