passwords:
    root: ENC[AES256_GCM,data:m3X/Rf4x3Z1Kq9U7D5jOcqjr0A8BhvVu87S4B+M4jlK7VqlVw4D4Sps/2bHbp/za9QubIjpagczM5tw7qpb5KFjLTwgJbVh+XA==,iv:1e4+I5c3EiTzMi++adSqFEJidFSjfO+f55rALfBl1YA=,tag:ZSnK/JIAF/wi9J7i4C6rCw==,type:str]
    m00n: ENC[AES256_GCM,data:tODTilUrPxbjdRJ7Lc0aPlQ8lmg2TATNRgX+t3Gdz6alPTW0DiHncpYu1SoTLk6luZQMzzRSiNp9mfmd7W/dDx/CjzASHFhqxA==,iv:5xj+h7bIUkfv+qMnXBDuVFg/Qhgq2tHUeCperxOh9zE=,tag:a9c49zQR/2nctYhWBdMccg==,type:str]
atuin:
    session: ENC[AES256_GCM,data:FAdCG1Ija26ay5uQP4slLyCZMO5udAS1d0Rxaqk6s+Y=,iv:5Ac0dvAufjJvqIWuvY8P2mIgMYfX4LWkVdmmQDCYXU0=,tag:PEcqxwsxgMLfjPtwM71G3A==,type:str]
sops:
    age:
        - recipient: age1gwv3knvgfrk26ythtrs2ed4235x8tu79lad459vx3e92krth6phq6t3ca3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWW5zY1I2REFrSXROdHNX
            dmtBeHU3M1R3aENSUS9wcVBJOG1CMHV3RWpzCm1OdzV6dms4M2M0QlU2dUlPMnNM
            V0s2Rm5Wc1dtVFRqNGVUV2pCQ051Q28KLS0tIGlHdkJIR25jcVl5RXRUMkdtTlpp
            dlRuazFVNUlkMTgvRzdtcDBlVTZmM0UKsErsPzCSZvRAfElqDiHLXaNmPsGQq3P0
            uwpoU1wbLtZG4wp8AWpa1PQqz5qS92gyinMXIOQBqX/tP+UuvedXBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T23:57:38Z"
    mac: ENC[AES256_GCM,data:Wdo6ga5wgEwaq4aiOuFDkjS2OqHbd37Uvv+LK0Jaq5TdiA/uf85ZCiMf1rX9x+n+QTf5381dr9Gt5rzbbpGesH2FTGtqKr2d87zGPclbXbsRNsOWvCha0YmCi5H9HVzjAlqzUZY9DuUgRDbrnr/v4iekHGVFeJNvIrHVo7gLKSQ=,iv:ZC7TkLncBv65USE9ZDim8SZKpzS07l8ZrOYYhLh41tc=,tag:SCVBQh05ld3GXmyWG+4S/A==,type:str]
    pgp:
        - created_at: "2025-05-03T18:05:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC0EwVK2S0BUSAQdAOZ/bw8DtO7lHlv2HZV4EZd+T7BtWqLr0p0WDYL9kLFMw
            6tu54173GHI4OEmHoNaxuxwTviWNKg6Vl6a2iqYTCOb7is+rrxBMqlMqIKOxRem1
            0l4BtrKZ3cjV1prJUgASfAYz23m4XVOcVrPPj++svRa4g1vhxip6TrL03latn5bv
            ct9TSTiRDXhzISiZxToPvkA6r4mbm0MD9kvkxTRR4yRIOpFBXLIZoaZr3eDWwSLU
            =USTc
            -----END PGP MESSAGE-----
          fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
    unencrypted_suffix: _unencrypted
    version: 3.11.0
