context7_api_key: null
sops:
    age:
        - recipient: age1gwv3knvgfrk26ythtrs2ed4235x8tu79lad459vx3e92krth6phq6t3ca3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLV1NBcFRKanYvTEtjZHZE
            WVk4cnROcnpnNU5KL0xUYUp4ZmxVbEZOcVU4CnR6bzdlbnZmQ1NhSUJsaDM1cm51
            UlRFQ2kwWlpYSEVuTmRrdFJDazRPUHcKLS0tIHMzUlJOa3loZUgzbVlrc2FFZTVo
            NjhrU0E1M29CSkVZVGtMNWc4MUNrOEEKAPBz5clVyGlbBoF3+YY35THsJLjruEy3
            HdA9dw8sR9tQ1p0kQafblnNCLRwVGrlzfCSD8pC/kBo7tSo0jJZN8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g75gk36leqv55yjdu2ulxutnkgye9f82ezhrkcllss3wejc6wewq6kyavs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSc2FZUWxOQ3VySG5VWEtT
            bUdnaHQ2dlNEUld6aDhGMlF3OVZOWjg2WVFNCkI4K2F2MkVRQk81ZmJIMHZjbDN5
            KzNVTmJTWC9QblVDVmh1VDcxMTZGUHMKLS0tIDZNdUlVY0ZsaFI0SnZYcytaOW0r
            OWhXRGZGMFBXTThKN3lYeHRyMWJGZlEKMUXI2RD1LxxNW9Stvb8EFi95csSzpmTk
            KrwMehXBFPgKC15xYd6fHWTS9j+4jSZ8Lz1/D7OGGcKvrUoJ9pZIfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T07:58:19Z"
    mac: ENC[AES256_GCM,data:ONJE6NBNX+aYJBEcWOKHgqfZA2a7nlO5WoJ/gchxKqN/ue3n2amsO/Yebf8V9hOYd3bnjcj0Q2BAigc0ES9CZBGva+FKsoBnZUgcxHhC7F98vWKOb4XfYn0SSu6ED1VUjYvuBhXQtxyWvkG2fOj3z6UUlRN7JyIlj+e942IODY4=,iv:Qym8E/eD+J67f/KwzYcTLM1vuaRnKIXTSLgAek7PusY=,tag:micxz+kLLnjoByk2rt1lLg==,type:str]
    pgp:
        - created_at: "2026-03-13T07:55:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC0EwVK2S0BUSAQdA2OGkP2PogbVi+CEiE8zI/gdWi3InTAxqFez1RwlaCGow
            LrDrL9j9ab3NrRwKSnv/NPVN8+MOwb8+kEMzF7fogj+xkQeZ4MTPhLbHP/pwWNFQ
            0l4B5A/5JfJV/HCyWJQHy8TDhCrrqQFoEJ7rZJLkou36cIkq83AkyjJ8xBvlwG2s
            GNP0Xkh0OgzK4wHzX8SJkrHfa4uFvdD+DeItC4QwSCLjy+Bd0msxSAdfXHSAZAw0
            =EB2h
            -----END PGP MESSAGE-----
          fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
    unencrypted_suffix: _unencrypted
    version: 3.12.1
